### ISSUE TITLE
Canal do discord na página "https://negros.dev/como-contribuir" está inválido

### ISSUE THREAD

**Issue by PabloEmidio** [negrosdev/negros.dev#17]
Acho que o título é autoexplicativo, mas como um compremento gostaria de ressaltar que a mensagem que aparece quando clica no link é **_"This invite may be expired, or you might not have permission to join."_**

**Comment by marcuxyz** [comment]
Opa, obrigado @PabloEmidio . Vou dá conferida :)

**Comment by marcuxyz** [comment]
@PabloEmidio problema resolvido :)
